management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"   # expose specific endpoints



resilience4j:
  retry:
    instances:
      inventoryRetry:
        maxRetryAttempts: 3
        waitDuration: 5s

  ratelimiter:
    instances:
      inventoryRateLimiter:
        limitRefreshPeriod: 5s
        limitForPeriod: 1
        timeoutDuration: 1s

  circuitbreaker:
    instances:
      inventoryCircuitBreaker:
        registerHealthIndicator: true   # check health endpoint
        slidingWindowType: COUNT_BASED   # TIME_BASED
        slidingWindowSize: 5             # size of the window for call recording
        minimumNumberOfCalls: 5         # Minimum number of calls before calculating failure rate
        permittedNumberOfCallsInHalfOpenState: 3   # number of calls when in half-open state
        waitDurationInOpenState: 20s            # time to wait before transitioning from open to half-open state
        failureRateThreshold: 50       # percentage of failures to trip the circuit
        eventConsumerBufferSize: 10     # size of the event buffer
